"""Regenerates score_norms.py: the average score of every dimension across all completed assessments.

Run from the backend folder after a few hundred more people have taken the assessment (the norms only need refreshing
occasionally):   python scripts/compute_score_norms.py

Why it exists: nearly everyone scores high on a few dimensions (national contribution, learning, investigative...), so
a plain "highest scores" list gives almost everyone the same profile, with frequent ties. scoring_engine uses these
averages to give a small credit for standing out from the typical person (see NORM_WEIGHT there).
"""
import os
import statistics
from collections import defaultdict

from dotenv import load_dotenv
from supabase import create_client

load_dotenv(".env")
sb = create_client(os.environ["SUPABASE_URL"], os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ["SUPABASE_KEY"])

rows, offset = [], 0
while True:
    batch = sb.table("assessment_results").select("response_id,framework,dimension,normalized_score").range(offset, offset + 999).execute().data
    rows += batch
    offset += 1000
    if len(batch) < 1000:
        break

by_dim = defaultdict(list)
for r in rows:
    by_dim[(r["framework"], r["dimension"])].append(float(r["normalized_score"]))
people = len({r["response_id"] for r in rows})

lines = [
    '"""Average score (0-100) of each dimension across completed assessments. Generated by scripts/compute_score_norms.py;',
    f'do not edit by hand. Based on {people} assessments."""',
    "",
    "POPULATION_MEANS = {",
]
for (fw, dim), vals in sorted(by_dim.items()):
    lines.append(f'    ("{fw}", "{dim}"): {round(statistics.mean(vals), 1)},')
lines.append("}")
with open(os.path.join(os.path.dirname(__file__), "..", "score_norms.py"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"score_norms.py written from {people} assessments, {len(by_dim)} dimensions")
