"""Regenerates career_popularity.py: for every career, the share of past assessments that had it in their top 8.

Run from the backend folder (occasionally; after a few hundred more assessments):
    PYTHONPATH=. python scripts/compute_career_popularity.py

The shares are measured with the popularity penalty switched OFF, so they describe how the plain matching behaves
(measuring with it on would make the numbers chase their own tail). See POPULARITY_WEIGHT in scoring_engine.py.
"""
import os
from collections import Counter, defaultdict

from dotenv import load_dotenv
from supabase import create_client

load_dotenv(".env")
import scoring_engine as se

sb = create_client(os.environ["SUPABASE_URL"], os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ["SUPABASE_KEY"])


def load_people():
    """[(profile row, score rows, cached semantic scores)] for every completed assessment that has scores."""
    scores, offset = defaultdict(list), 0
    while True:
        batch = sb.table("assessment_results").select("response_id,framework,dimension,normalized_score").range(offset, offset + 999).execute().data
        for r in batch:
            scores[r["response_id"]].append({**r, "normalized_score": float(r["normalized_score"])})
        offset += 1000
        if len(batch) < 1000:
            break
    people = []
    ids = list(scores)
    for i in range(0, len(ids), 25):
        for p in sb.table("assessment_responses").select(
                "id,education_field,career_direction,sectors_of_interest,current_stage,experience_level,answers,career_semantic_scores_cache"
        ).in_("id", ids[i:i + 25]).execute().data:
            people.append((p, scores[p["id"]], p.get("career_semantic_scores_cache") or {}))
    return people


def top8_counts(people, careers):
    counts = Counter()
    for profile, rows, semantic in people:
        summary = se.build_framework_output(rows)
        for c in se.score_careers(summary, profile, careers, semantic)[:8]:
            counts[c["title"]] += 1
    return counts


if __name__ == "__main__":
    se.POPULARITY_WEIGHT = 0.0
    careers = sb.table("careers").select("*").eq("is_approved", True).execute().data
    people = load_people()
    counts = top8_counts(people, careers)
    shares = {title: round(n / len(people), 3) for title, n in counts.items()}
    lines = [
        '"""Share (0-1) of past assessments that had each career in their top 8, measured without the popularity penalty.',
        f'Generated by scripts/compute_career_popularity.py from {len(people)} assessments; do not edit by hand."""',
        "",
        "CAREER_SHARE = {",
    ]
    for title, share in sorted(shares.items(), key=lambda x: -x[1]):
        lines.append(f"    {title!r}: {share},")
    lines.append("}")
    with open(os.path.join(os.path.dirname(__file__), "..", "career_popularity.py"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"career_popularity.py written from {len(people)} assessments; top: {counts.most_common(6)}")
